# HERE GOES DATA FOR LANGUAGES AND LANGUAGE TRANSLATION
# MAKE IT A CLASS


languages = {
    'eng': {
        'LOAD FILE': 'Load File',
        "File name:": "File name:",
        'CHANGE FILE': 'CHANGE FILE',
        'SHOW TABLE': 'SHOW TABLE',
        'SELECT COLUMN': 'SELECT COLUMN',
        'HIDE TABLE': 'HIDE TABLE',
        'HIDE COLUMNS': 'HIDE COLUMNS',
        'OK': 'OK',
        'get_highest_value': 'get_highest_value',
        'get_lowest_value': 'get_lowest_value',
        'get_average': 'get_average',
        'unique_values': 'unique_values',
        "The highest value in column ": "The highest value in column",
        'The lowest value in column ': 'The lowest value in column ',
        "HIDE": "HIDE",
        'The average value in column ': 'The average value in column ',
        'The median value in column ': 'The median value in column ',
        'get_median': 'get_median',
        'get_most_frequent': 'get_most_frequent',
        'The most frequent value in column ': 'The most frequent value in column ',
        "Error": "Error",
        "An error occurred": "An error occurred",
        'wrong file extension': 'wrong file extension',
        "get_standard_deviation": "get_standard_deviation",
        "The standard deviation value in column ": "The standard deviation value in column ",
        'get_variance': 'get_variance',
        'The variance in column ': 'The variance in column ',
        'get_percentiles': 'get_percentiles',
        'GO TO\nADVANCED\nANALYSIS': 'GO TO\nADVANCED\nANALYSIS',
        'GO TO\nBASIC\nANALYSIS': 'GO TO\nBASIC\nANALYSIS',
        "Basic Analysis": 'Basic Analysis',
        "Advanced Analysis": 'Advanced Analysis',
        'SELECT COLUMNS': 'SELECT COLUMNS',
        'PLEASE SELECT AT LEAST TWO COLUMNS': 'PLEASE SELECT AT LEAST TWO COLUMNS',
        'sum_row_vals_in_columns': 'sum_row_vals_in_columns',
        'mean_row_vals_in_columns': 'mean_row_vals_in_columns',
        'median_row_vals_in_columns': 'median_row_vals_in_columns',
        'Save': 'Save',
        'Data saved successfully': 'Data saved successfully',
        'Filename': 'Filename',
        'Enter filename (without extension):': 'Enter filename (without extension):',
        'concat_row_vals_in_columns': 'concat_row_vals_in_columns',
        'Please select at least 2 columns': 'Please select at least 2 columns',
        'product_row_vals_in_columns': 'product_row_vals_in_columns',
    },
    'pl': {
        'LOAD FILE': '___PL___',
        "File name:": '___PL___',
        'CHANGE FILE': '___PL___',
        'SHOW TABLE': '___PL___',
        'SELECT COLUMN': '___PL___',
        'HIDE TABLE': '___PL___',
        'HIDE COLUMNS': '___PL___',
        'OK': 'OK',
        'get_highest_value': '___PL___',
        'get_lowest_value': '___PL___',
        'get_average': '___PL___',
        'unique_values': '___PL___',
        "The highest value in column ": '___PL___',
        'The lowest value in column ': '___PL___',
        "HIDE": '___PL___',
        'The average value in column ': '___PL___',
        "get_median": '___PL___',
        'The median value in column ': '___PL___',
        'get_most_frequent': '___PL___',
        'The most frequent value in column ': '___PL___',
        "Error": '___PL___',
        "An error occurred": '___PL___',
        'wrong file extension': '___PL___',
        "get_standard_deviation": '___PL___',
        "The standard deviation value in column ": '___PL___',
        'get_variance': '___PL___',
        'The variance in column ': '___PL___',
        'get_percentiles': '___PL___',
        'GO TO\nADVANCED\nANALYSIS': '___PL___',
        'GO TO\nBASIC\nANALYSIS': '___PL___',
        "Basic Analysis": '___PL___',
        "Advanced Analysis": '___PL___',
        'SELECT COLUMNS': '___PL___',
        'PLEASE SELECT AT LEAST TWO COLUMNS': '___PL___',
        'sum_row_vals_in_columns': '___PL___',
        'mean_row_vals_in_columns': '___PL___',
        'median_row_vals_in_columns': '___PL___',
        'Save': '___PL___',
        'Data saved successfully': '___PL___',
        'Filename': '___PL___',
        'Enter filename (without extension):': '___PL___',
        'concat_row_vals_in_columns': '___PL___',
        'Please select at least 2 columns': '___PL___',
        'product_row_vals_in_columns': '___PL___',

    },
    'es': {
        'LOAD FILE': 'ABRIR ARCHIVO',
        "File name:": 'Nombre del archivo:',
        'CHANGE FILE': 'CAMBIAR ARCHIVO',
        'SHOW TABLE': 'MOSTRAR TABLA',
        'SELECT COLUMN': 'SELECCIONAR COLUMNA',
        'HIDE TABLE': 'OCULTAR TABLA',
        'HIDE COLUMNS': 'OCULTAR COLUMNAS',
        'OK': 'OK',
        'get_highest_value': 'obtener valor más alto',
        'get_lowest_value': 'obtener valor más bajo',
        'get_average': 'obtener promedio',
        'unique_values': 'valores unicos',
        "The highest value in column ": 'El valor más alto en la columna ',
        'The lowest value in column ': 'El valor más bajo en la columna ',
        "HIDE": 'ESCONDER',
        'The average value in column ': 'El valor promedio en la columna ',
        "get_median": 'obtener mediana',
        'The median value in column ': 'El valor mediano en la columna ',
        'get_most_frequent': 'obtener más frecuente',
        'The most frequent value in column ': 'El valor más frecuente en la columna ',
        "Error": 'Error',
        "An error occurred": 'An error occurred',
        'wrong file extension': 'extensión de archivo incorrecta',
        "get_standard_deviation": 'get desviación estándar',
        "The standard deviation value in column ": 'El valor de la desviación estándar en la columna ',
        'get_variance': 'obtener varianza',
        'The variance in column ': 'La varianza en la columna ',
        'get_percentiles': 'obtener percentiles',
        'GO TO\nADVANCED\nANALYSIS': 'IR A\nANÁLISIS AVANZADO',
        'GO TO\nBASIC\nANALYSIS': 'IR A\nANÁLISIS BÁSICO',
        "Basic Analysis": 'Análisis básico',
        "Advanced Analysis": 'Análisis avanzado',
        'SELECT COLUMNS': 'SELECCIONAR COLUMNAS',
        'PLEASE SELECT AT LEAST TWO COLUMNS': 'POR FAVOR SELECCIONE AL MENOS DOS COLUMNAS',
        'sum_row_vals_in_columns': 'suma valores en columnas',
        'mean_row_vals_in_columns': '___ES___',
        'median_row_vals_in_columns': 'mediana en columnas',
        'Save': 'Guardar',
        'Data saved successfully': 'Datos guardados exitosamente',
        'Filename': '___ES___',
        'Enter filename (without extension):': 'Nombre del archivo (sin extensión)',
        'concat_row_vals_in_columns': '___ES___',
        'Please select at least 2 columns': 'Por favor seleccione al menos 2 columnas',
        'product_row_vals_in_columns': '___ES___',

    }
}


class LanguageCenter:
    def __init__(self):
        # HARD CODED FOR TESTING
        self.language = languages['eng']


    def translate(self, word):
        translated = self.language[word]
        return translated